### PR TITLE
fix: static props inference

### PR DESCRIPTION
**Pull request by bautistaaa**
### Description
Example was not inferring static props and resulting in `never`

Found this gem buried in an issue and applied the same solution here
https://github.com/vercel/next.js/issues/15913#issuecomment-911684434

image

### CODE REVIEW

**Comment by bautistaaa** [comment]
cc @KATT

**Review by KATT — DISMISSED** [review]

**Comment by KATT** [comment]
@bautistaaa seems to have some `prettier` issues :)

**Comment by KATT** [comment]
also, if the example is using a helper, it should probably be included in the paths that are displayed on the page

**Comment by KATT** [comment]
See https://github.com/trpc/examples-kitchen-sink/blob/main/src/feature/ssg/meta.tsx

**Comment by bautistaaa** [comment]
> See https://github.com/trpc/examples-kitchen-sink/blob/main/src/feature/ssg/meta.tsx

Was this what you had in mind? Added a SS to the PR description as well

1f21578

**Review by KATT — APPROVED** [review]

**Comment by bautistaaa** [comment]
@KATT looks like e2e is stuck 😬

**Pull request closed without merging**
