### PR TITLE
Next Auth Authentication Feature

### PR DESCRIPTION
**Pull request by ShiftySlothe**
Added basic examples of authentication using next-auth. 

Shown client side hook, server side context check and middleware context check with a TRPCError. 

image

image

Next-Auth has been added to the project and three basic examples of use are displayed. Github OAuth credentials (GITHUB_ID, GITHUB_SECRET) and a secret (NEXTAUTH_SECRET) will need to be added to the environment variables for this to work. 

I have included the context file to show how you add the session to the context for backend work. I had attempted to write a custom context file for the router specific to this feature, however I was unable to merge the router with the app router as the context object type was conflicting. 

If anyone has any feedback in terms of changes to the current examples or additional examples I would be grateful to hear it.  e.g. Could persist the user via Prisma.

### CODE REVIEW

**Comment by ShiftySlothe** [comment]
@KATT Actioned everything in the old PR, will delete now. I have just used a dummy credentials provider for now.

**Comment by KATT** [comment]
For next PR, please push straight to this repo! [Accept your invitation](https://github.com/trpc/examples-kitchen-sink/invitations) :)

**Comment by KATT** [comment]
Thank you so much for doing this! ❤️

**Comment by KATT** [comment]
And apologies on the delay, this slipped my mind! :)

**Pull request merged**
